### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by yurivict** [TRIQS/cpp2py#39]
The latest tag ```py2_compat``` suggests that you are currently Python-2 compatible? But Python-2 is EOLed.

**Comment by Wentzell** [comment]
Dear @yurivict,

The current version of cpp2py is based on Python 3.
The `py2_compat` tag is just denoting the last commit before the switch to Python 3.

I have tagged the prerelease [2.0-rc1](https://github.com/TRIQS/cpp2py/releases/tag/2.0-rc1), the 2.0.0 release will follow in the next weeks.
