### ISSUE TITLE
Installs the file share/cpp2pyvars.sh

### ISSUE THREAD

**Issue by yurivict** [TRIQS/cpp2py#41]
Normally files should be installed under ```share/cpp2py/```. Also, is this file needed?

Version 2.0.0

**Comment by Wentzell** [comment]
This file is provided to easily load a cpp2py installation into your shell environment.

I agree that the file should be installed into a subdirectory of `share`.
I have introduced this change in 591dc97.
I have also added a check that will skip the installation when installing into a system directory,
that is either `/usr` or `/usr/local`

**Comment by Wentzell** [comment]
@yurivict Can this be closed?
