### ISSUE TITLE
[cmake] python virtual environments are currently ignored

### ISSUE THREAD

**Issue by the-hampel** [TRIQS/cpp2py#50]
Currently cpp2py uses a custom `find_package(python)` module that became quite old. Newer features like the configuration variable for virtual environments `Python_FIND_VIRTUALENV` are missing. Currently that means that triqs / cpp2py will completely ignore virutal environments and instead picks the python interpreter behind the venv. This means that all custom installed pip packages in this venv are not found! 

Possible solution: remove custom find python package in `cmake/FindPython.cmake`.

**Comment by Wentzell** [comment]
Thank you @the-hampel for pointing this out. This is now fixed on unstable by using the cmake FindPython module.
