### ISSUE TITLE
[Doc] standalone example?

### ISSUE THREAD

**Issue by tayral** [TRIQS/cpp2py#6]
Hi,
Is there somewhere a minimal standalone example, ie an example with a simple c++ class and the corresponding CMakeLists.txt?
I started thinking about it but my CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.5)
if(COMMAND cmake_policy)
   cmake_policy(SET CMP0003 OLD)
endif(COMMAND cmake_policy)

set(CPP2PY_ADD_MODULE_ADDITIONAL_PYTHONPATH "/home/tayral/Work/TRIQS_1.6/install_cpp2py/lib/python2.7/site-packages/")
include(${CPP2PY_PATH}/share/cmake/Cpp2PyConfig.cmake)
include_directories(${CPP2PY_PATH}/include)
include_directories(.)
add_cpp2py_module(myclass) #I have generated a myclass_desc.py file with cpp2py
```
yields errors (one is: there is a TRIQS_RUNTIME_ERROR in the cxx file... but one does not necessarily want to use TRIQS)
Thanks

**Comment by tayral** [comment]
Any idea here?

**Comment by Wentzell** [comment]
The documentation is still outstanding.

However we are currently updating the Skeleton for TRIQS + cpp2py applications. I will make you a temporary version available via mail for now!

**Comment by tayral** [comment]
OK, thanks. Thanks to your example, I could compile my small example, which I provided in my fork (see my pull request).
